                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </section>
    </body>
</html>
<?
$cfg->close();
?>
